name: Build
on: [push, pull_request]

jobs:
  test:
    name: Run Unit Tests
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
        
      - name: Run Unit tests
        run: ./gradlew test --stacktrace

      - name: Run Android tests
          uses: reactivecircus/android-emulator-runner@v1
          with:
            api-level: 29
            script: ./gradlew connectedCheck --stacktrace